const ACTIONS = {
  ADD_TRANSACTION: "ADD_TRANSACTION",
  REMOVE_TRANSACTION: "REMOVE_TRANSACTION",
  EDIT_TRANSACTION: "EDIT_TRANSACTION",
  GET_TRANSACTION: "GET_TRANSACTION",
  USER_SIGNIN: "USER_SIGIN",
  USER_SIGNUP: "USER_SIGNUP",
};

module.exports = { ACTIONS };
